AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  NewCops: disable
  Include:
    - '**/*.lic'
    - '**/*.rb'

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
  
Metrics/ParameterLists:
  Enabled: false

Naming:
  Enabled: false

Security/Eval:
  Enabled: false
  
Security/MarshalLoad:
  Enabled: false

Style:
  Enabled: false
