{
  schema_version: 3,
  name: "fire elemental",
  noun: "elemental",
  url: "https://gswiki.play.net/fire_elemental",
  picture: "",
  level: 60,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: false,
  limbs: nil,
  witherable: false,
  sympathy: true,
  muggable: nil,
  sleepable: nil,
  boss: false,
  boss_type: nil,
  otherclass: [
    "Extraplanar",
    "Magical"
  ],
  bcs: true,
  max_hp: 260,
  speed: 12,
  height: 6,
  size: "medium",
  areas: [
    {
      name: "Eye of V'Tull",
      uids: [3060002..3060018, 3061001..3061028]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Ensnare",
        as: 346
      }
    ],
    bolt_spells: [],
    warding_spells: [],
    offensive_spells: [
      {
        name: "Major Elemental Wave"
      }
    ],
    maneuvers: [],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: "10N",
    immunities: [],
    melee: (276..446),
    ranged: (263..300),
    bolt: (263..300),
    udf: (341..346),
    bar_td: nil,
    cle_td: 237,
    emp_td: (234..260),
    pal_td: (212..215),
    ran_td: (200..209),
    sor_td: (248..260),
    wiz_td: nil,
    mje_td: nil,
    mne_td: nil,
    mjs_td: 263,
    mns_td: 263,
    mnm_td: 200,
    defensive_spells: [],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: nil,
    boxes: nil,
    skin: nil,
    other: nil,
    armaments: nil,
    transmogs: nil
  },
  messaging: {
    description: [
      "The fire elemental is a massing of flames that flow and flicker with a life of their own. The intense heat generated by the fire elemental is nearly unbearable."
    ],
    arrival: [
      "A fire elemental blazes in, leaving the ground scorched in {pronoun} wake!"
    ],
    flee: [
      "A fire elemental blazes {direction}, scorching the earth in {pronoun} wake."
    ],
    death: [
      "The fire elemental sputters violently, cascading flames all around as it collapses in a final fiery display."
    ],
    decay: [],
    search: [],
    spell_prep: [
      "A fire elemental flares brightly, extending a fiery tendril towards you!",
      "A fire elemental flares brighter, an extension reaching towards you!",
      "A fire elemental flares brighter, extending a fiery tendril towards {target}!"
    ],
    attacks: {
      attack: [
        "A fire elemental flares brighter, an extension reaching towards you!",
        "A fire elemental flares brightly, extending a fiery tendril towards you!",
        "A fire elemental focuses {pronoun} energies at you!",
        "A fire elemental lashes out at you!"
      ]
    },
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
