{
  schema_version: 3,
  name: "huge ice elemental",
  noun: "elemental",
  url: "https://gswiki.play.net/huge_ice_elemental",
  picture: "",
  level: 95,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: nil,
  bones: nil,
  limbs: nil,
  witherable: nil,
  sympathy: nil,
  muggable: nil,
  sleepable: nil,
  boss: false,
  boss_type: nil,
  otherclass: [
    "Extraplanar",
    "Magical"
  ],
  bcs: true,
  max_hp: 300,
  speed: nil,
  height: nil,
  size: "",
  areas: [
    {
      name: "Elemental Confluence",
      uids: [580001..580025, 581001..581025, 582001..582025, 583001..583025, 584001..584025, 585001..585025, 586001..586025, 587001..587025, 588001..588025]
    },
    {
      name: "unmapped",
      uids: [4070501..4070519]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Pound",
        as: 430
      }
    ],
    bolt_spells: [
      {
        name: "Major Cold (907)",
        as: 438
      },
      {
        name: "Minor Cold (1709)",
        as: 438
      }
    ],
    warding_spells: [],
    offensive_spells: [],
    maneuvers: [
      {
        name: "Slush wall"
      }
    ],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: "10",
    immunities: [],
    melee: nil,
    ranged: (299..363),
    bolt: (299..363),
    udf: nil,
    bar_td: 485,
    cle_td: 400,
    emp_td: 400,
    pal_td: nil,
    ran_td: (348..357),
    sor_td: nil,
    wiz_td: nil,
    mje_td: nil,
    mne_td: nil,
    mjs_td: 400,
    mns_td: 400,
    mnm_td: nil,
    defensive_spells: [
      "Elemental Barrier",
      "Elemental Bias",
      "Elemental Defense I",
      "Elemental Defense II",
      "Elemental Defense III",
      "Elemental Targeting"
    ],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: true,
    boxes: nil,
    skin: nil,
    other: "essence of water",
    armaments: nil,
    transmogs: nil
  },
  messaging: {
    description: [
      "The ice elemental is an amorphous conglomeration of ice and snow that writhes and moves about with a mind of its own. The intense cold generated by the ice elemental is nearly unbearable."
    ],
    arrival: [],
    flee: [
      "A huge ice elemental flows {direction}, followed by a hailing icestorm.",
      "A huge ice elemental flows {direction}, followed by a hailing icestorm!"
    ],
    death: [
      "The ice elemental dissipates into a cool breeze that fades rapidly away."
    ],
    decay: [],
    search: [],
    spell_prep: [
      "A huge ice elemental glows with a bright blue light."
    ],
    attacks: {
      attack: [
        "A huge ice elemental pounds at you with an icy fist!"
      ]
    },
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
