{
  schema_version: 3,
  name: "huge fire elemental",
  noun: "elemental",
  url: "https://gswiki.play.net/huge_fire_elemental",
  picture: "",
  level: 99,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: nil,
  bones: nil,
  limbs: nil,
  witherable: nil,
  sympathy: nil,
  muggable: nil,
  sleepable: nil,
  boss: false,
  boss_type: nil,
  otherclass: [
    "Extraplanar",
    "Magical"
  ],
  bcs: true,
  max_hp: 300,
  speed: nil,
  height: 15,
  size: "huge",
  areas: [
    {
      name: "Elemental Confluence",
      uids: [580026..580053, 581026..581053, 582026..582053, 583026..583053, 584026..584053, 585026..585053, 586026..586053, 587026..587053, 588026..588053]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Claw",
        as: 460
      },
      {
        name: "Roaring ball of fire",
        as: 469
      },
      {
        name: "Stream of fire",
        as: 469
      }
    ],
    bolt_spells: [
      {
        name: "Major Fire (908)",
        as: 469
      },
      {
        name: "Minor Fire (906)",
        as: 469
      }
    ],
    warding_spells: [],
    offensive_spells: [],
    maneuvers: [
      {
        name: "Mass Boil Earth"
      },
      {
        name: "Lash"
      }
    ],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: "10",
    immunities: [],
    melee: nil,
    ranged: (296..299),
    bolt: (296..307),
    udf: nil,
    bar_td: 403,
    cle_td: 428,
    emp_td: 428,
    pal_td: nil,
    ran_td: nil,
    sor_td: nil,
    wiz_td: nil,
    mje_td: nil,
    mne_td: nil,
    mjs_td: 428,
    mns_td: 428,
    mnm_td: nil,
    defensive_spells: [
      "Elemental Barrier",
      "Elemental Bias",
      "Elemental Defense I",
      "Elemental Defense II",
      "Elemental Defense III",
      "Elemental Targeting"
    ],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: true,
    boxes: nil,
    skin: nil,
    other: "essence of fire",
    armaments: nil,
    transmogs: nil
  },
  messaging: {
    description: [
      "The fire elemental is a massing of flames that flow and flicker with a life of their own. The intense heat generated by the fire elemental is nearly unbearable."
    ],
    arrival: [
      "A huge fire elemental blazes in, leaving the ground scorched in {pronoun} wake!"
    ],
    flee: [
      "A huge fire elemental blazes {direction}, scorching the ground in {pronoun} wake."
    ],
    death: [
      "The fire elemental sputters violently, cascading flames all around as it collapses in a final fiery display."
    ],
    decay: [],
    search: [],
    spell_prep: [],
    attacks: {
      attack: [
        "A huge fire elemental rakes at you with tendrils of flame!",
        "The fire elemental absorbs the elemental essence of the spell and appears energized!",
        "The fire elemental barely dodges the missile!"
      ],
      claw: [
        "A huge fire elemental rakes at you with tendrils of flame!"
      ],
      hurl: [
        "A huge fire elemental hurls {weapon} at you!"
      ]
    },
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
