{
  schema_version: 3,
  name: "ki-lin",
  noun: "",
  url: "https://gswiki.play.net/ki-lin",
  picture: "",
  level: nil,
  family: "",
  type: "",
  undead: false,
  has_blood: nil,
  has_bones: nil,
  muggable: nil,
  boss: false,
  otherclass: [],
  bcs: nil,
  max_hp: nil,
  speed: nil,
  height: nil,
  size: "",
  areas: [],
  attack_attributes: {
    physical_attacks: [],
    bolt_spells: [],
    warding_spells: [],
    offensive_spells: [],
    maneuvers: [],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: nil,
    immunities: [],
    melee: nil,
    ranged: nil,
    bolt: nil,
    udf: nil,
    bar_td: nil,
    cle_td: nil,
    emp_td: nil,
    pal_td: nil,
    ran_td: nil,
    sor_td: 117,
    wiz_td: nil,
    mje_td: nil,
    mne_td: nil,
    mjs_td: nil,
    mns_td: nil,
    mnm_td: nil,
    defensive_spells: [],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: nil,
    boxes: nil,
    skin: "a ki-lin horn",
    other: nil
  },
  messaging: {
    description: [
      "Imagine a creature with the head of a dragon, the mane of a lion, the body of a stag and the tail of an ox. Add a solitary horn upon its forehead and the form of the ki-lin is complete. Sightings of this magical and dangerous beast are very rare and thus trophy hunters are said to pay a high price for the horn of the legendary beast."
    ],
    arrival: [],
    flee: [],
    death: [],
    decay: [],
    search: [],
    spell_prep: [],
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
