{
  schema_version: 3,
  name: "lesser ice elemental",
  noun: "elemental",
  url: "https://gswiki.play.net/lesser_ice_elemental",
  picture: "",
  level: 53,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: false,
  limbs: nil,
  witherable: false,
  sympathy: true,
  muggable: true,
  sleepable: nil,
  boss: false,
  boss_type: nil,
  otherclass: [
    "Extraplanar",
    "Magical"
  ],
  bcs: true,
  max_hp: 400,
  speed: nil,
  height: 5,
  size: "large",
  areas: [
    {
      name: "Great Mountain Aenatumgana",
      uids: [4561102..4561141]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Ensnare"
      },
      {
        name: "Lash",
        as: (255..301)
      }
    ],
    bolt_spells: [
      {
        name: "Minor Cold (1709)",
        as: 251
      }
    ],
    warding_spells: [],
    offensive_spells: [
      {
        name: "Elemental Dispel (417)"
      },
      {
        name: "Elemental Wave (410)"
      },
      {
        name: "Major Elemental Wave (435)"
      }
    ],
    maneuvers: [
      {
        name: "Ground Slam"
      }
    ],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: nil,
    immunities: [],
    melee: (262..386),
    ranged: (256..292),
    bolt: (256..302),
    udf: (327..416),
    bar_td: nil,
    cle_td: (204..214),
    emp_td: (203..204),
    pal_td: (181..191),
    ran_td: (163..168),
    sor_td: (216..223),
    wiz_td: nil,
    mje_td: (216..240),
    mne_td: (216..240),
    mjs_td: (203..211),
    mns_td: (203..211),
    mnm_td: 187,
    defensive_spells: [
      "Elemental Defense I (401)",
      "Elemental Defense II (406)",
      "Elemental Defense III (414)",
      "Prismatic Guard (905)"
    ],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: nil,
    boxes: nil,
    skin: nil,
    other: "essence of water",
    armaments: nil,
    transmogs: nil
  },
  messaging: {
    description: [
      "The ice elemental is an amorphous conglomeration of ice and snow that writhes and moves about with a mind of its own. The intense cold generated by the ice elemental is nearly unbearable."
    ],
    arrival: [],
    flee: [
      "A lesser ice elemental flows {direction}, followed by a hailing icestorm!",
      "A lesser ice elemental flows {direction}, followed by a hailing icestorm."
    ],
    death: [],
    decay: [],
    search: [],
    spell_prep: [
      "A lesser ice elemental glows with a bright blue light.",
      "A lesser ice elemental glows blue while absorbing the energy!"
    ],
    attacks: {
      attack: [
        "A lesser ice elemental releases a wave of cold blue energy at you!",
        "A lesser ice elemental lashes out at {target}!"
      ]
    },
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
