{
  schema_version: 3,
  name: "major glacei",
  noun: "glacei",
  url: "https://gswiki.play.net/major_glacei",
  picture: "",
  level: 47,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: false,
  limbs: nil,
  witherable: false,
  sympathy: true,
  muggable: true,
  sleepable: nil,
  boss: false,
  boss_type: nil,
  otherclass: [
    "Magical"
  ],
  bcs: true,
  max_hp: 240,
  speed: nil,
  height: 5,
  size: "medium",
  areas: [
    {
      name: "Great Mountain Aenatumgana",
      uids: [4561001..4561010]
    },
    {
      name: "Pinefar Forests",
      uids: [4563034..4563051]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Lash",
        as: 259
      },
      {
        name: "Strike",
        as: (234..281)
      }
    ],
    bolt_spells: [
      {
        name: "Major Cold (907)",
        as: 212
      }
    ],
    warding_spells: [],
    offensive_spells: [],
    maneuvers: [],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: nil,
    immunities: [],
    melee: (120..265),
    ranged: (145..180),
    bolt: (145..180),
    udf: (179..324),
    bar_td: (172..211),
    cle_td: (180..196),
    emp_td: (173..189),
    pal_td: (158..167),
    ran_td: 160,
    sor_td: (191..200),
    wiz_td: nil,
    mje_td: (206..212),
    mne_td: (206..212),
    mjs_td: (177..186),
    mns_td: (177..186),
    mnm_td: (155..165),
    defensive_spells: [],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: true,
    boxes: nil,
    skin: nil,
    other: "essence of water",
    armaments: nil,
    transmogs: nil
  },
  messaging: {
    description: [
      "The major glacei is a conglomeration of ice and snow that writhes and moves with a mind of its own formed in a vaguely humanoid shape. The cold generated by the major glacei is nearly unbearable."
    ],
    arrival: [],
    flee: [],
    death: [],
    decay: [],
    search: [],
    spell_prep: [
      "A major glacei flares with a deep blue glow.",
      "A major glacei glows blue while absorbing the energy!"
    ],
    attacks: {
      attack: [
        "A major glacei focuses a wave of cold energy at you!",
        "A major glacei lashes out at {target}!",
        "A major glacei strikes at {target}!"
      ],
      hurl: [
        "A major glacei hurls a chunk of ice at you!"
      ]
    },
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
