{
  schema_version: 3,
  name: "minor glacei",
  noun: "glacei",
  url: "https://gswiki.play.net/minor_glacei",
  picture: "",
  level: 42,
  family: "Elemental",
  type: "Elemental",
  undead: false,
  blood: false,
  bones: false,
  limbs: nil,
  witherable: false,
  sympathy: true,
  muggable: true,
  sleepable: nil,
  boss: false,
  boss_type: nil,
  otherclass: [
    "Magical"
  ],
  bcs: true,
  max_hp: 238,
  speed: 6,
  height: 5,
  size: "medium",
  areas: [
    {
      name: "Pinefar Forests",
      uids: [4563030..4563043]
    }
  ],
  attack_attributes: {
    physical_attacks: [
      {
        name: "Lash",
        as: (217..246)
      },
      {
        name: "Strike",
        as: (247..250)
      }
    ],
    bolt_spells: [],
    warding_spells: [],
    offensive_spells: [],
    maneuvers: [],
    special_abilities: [],
    special_notes: []
  },
  defense_attributes: {
    asg: nil,
    immunities: [],
    melee: (126..236),
    ranged: (146..167),
    bolt: (146..167),
    udf: 352,
    bar_td: 158,
    cle_td: (152..164),
    emp_td: (160..163),
    pal_td: (132..142),
    ran_td: (135..140),
    sor_td: (168..177),
    wiz_td: nil,
    mje_td: (158..178),
    mne_td: (158..178),
    mjs_td: 183,
    mns_td: 183,
    mnm_td: (131..141),
    defensive_spells: [],
    defensive_abilities: [],
    special_defenses: []
  },
  special_other: nil,
  abilities: [],
  alchemy: [],
  abilities_misc: [],
  equipment: [],
  treasure: {
    coins: nil,
    magic_items: nil,
    gems: true,
    boxes: nil,
    skin: nil,
    other: "essence of water",
    armaments: nil,
    transmogs: nil
  },
  messaging: {
    description: [
      "The minor glacei is a conglomeration of ice and snow that writhes and moves with a mind of its own formed in a vaguely humanoid shape. The cold generated by the minor glacei is nearly unbearable."
    ],
    arrival: [
      "A minor glacei slides in, followed by a hailing icestorm!"
    ],
    flee: [],
    death: [],
    decay: [],
    search: [],
    spell_prep: [
      "A minor glacei flares with a deep blue glow.",
      "A minor glacei glows blue while absorbing the energy!"
    ],
    attacks: {
      attack: [
        "A minor glacei lashes out at you!",
        "A minor glacei strikes at you!",
        "A minor glacei focuses a wave of cold energy at you!"
      ]
    },
    info: {
      general: [],
      class_tips: {
        cleric: [],
        paladin: [],
        ranger: [],
        bard: [],
        wizard: [],
        empath: [],
        rogue: [],
        warrior: [],
        sorcerer: []
      },
      miscellany: []
    },
    triggers: {}
  }
}
