name: Installer

on: 
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: write

jobs:
  installer:
    runs-on: windows-2022
    strategy:
      matrix:
        ruby: ['3.4.5']
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@16a9c90856f42705d54a6fda1823352bdc62cf38 # v1.267.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Create Core Lich-5 package
        id: install_core_scripts
        run: |
          mkdir Lich5
          mkdir Lich5/data
          mkdir Lich5/scripts
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/alias.lic > lich5/scripts/alias.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/autostart.lic > lich5/scripts/autostart.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/ewaggle.lic > lich5/scripts/ewaggle.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/go2.lic > lich5/scripts/go2.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/jinx.lic > lich5/scripts/jinx.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/lich5-update.lic > lich5/scripts/lich5-update.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/log.lic > lich5/scripts/log.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/map.lic > lich5/scripts/map.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/repository.lic > lich5/scripts/repository.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/vars.lic > lich5/scripts/vars.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/version.lic > lich5/scripts/version.lic
          curl https://raw.githubusercontent.com/elanthia-online/dr-scripts/master/dependency.lic > lich5/scripts/dependency.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/effect-list.xml > lich5/data/effect-list.xml
          cp lich.rbw Lich5/
          cp -r lib Lich5/
          ridk exec pacman -Syu --needed --noconfirm
          ridk exec pacman -S mingw-w64-x86_64-sqlite3 --noconfirm
          gem install sqlite3 --platform ruby
          gem install activesupport ascii_charts concurrent-ruby curses ftools gtk3 json jwt logger mechanize nokogiri ostruct redis sequel terminal-table tomlib tzinfo tzinfo-data webrick xmpp4r --no-document
          gem uninstall rexml --force
          gem install rexml --version 3.3.1
          gem list
          iscc "R4LGTK3.iss"
          mv .\Output\Ruby4Lich5.exe .\Ruby4Lich5.exe
      - name: Add to Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          files: |
            Ruby4Lich5.exe
