name: "Lint PR"

on:
  pull_request:
    branches:
      - staging
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        with:
          scopes: |
            all
            dr
            gs
            main
            pre\/beta.*
          requireScope: true
          disallowScopes: |
            [A-Z]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
