name: Rubocop
on: 
  push:
    branches:
      - master
      - staging
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"
  pull_request:
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.4']
    name: Run Rubocop on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Rubocop
        run: |
          bundle exec rubocop
