name: Rubocop
on: 
  push:
    branches:
      - master
      - staging
      - main
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"
  pull_request:
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    name: Run Rubocop on Ruby
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      
      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          bundler-cache: true

      - name: Rubocop
        run: |
          bundle exec rubocop
